# Generated by Django 3.2 on 2024-06-23 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0003_alter_aadhardetail_indian'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_no', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=40)),
                ('indian', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.indian')),
            ],
        ),
    ]
