# Generated by Django 3.2 on 2024-06-23 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_aadhardetail_indian'),
        ('new_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='indian',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.indian'),
        ),
    ]
