# Generated by Django 3.2 on 2024-06-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0002_washingmachine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='brand',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
