# Generated by Django 3.2 on 2024-06-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0003_alter_phone_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='washingmachine',
            name='brand',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
