# Generated by Django 3.2 on 2024-06-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0004_washingmachine_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='washingmachine',
            name='brand',
            field=models.CharField(max_length=32, null=True, verbose_name='Brand ka Name (Yaha daalo)'),
        ),
    ]
