# Generated by Django 3.2 on 2024-06-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_movie_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='type',
            field=models.CharField(choices=[['Action', 'ACTION'], ['Fiction', 'FICTION'], ['Horror', 'HORROR'], ['Comedy', 'COMEDY']], max_length=30),
        ),
    ]
