# Generated by Django 3.2 on 2024-06-23 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('age', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AadharDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar_no', models.CharField(max_length=16, unique=True)),
                ('aadhar_address', models.TextField()),
                ('aadhar_expiry_date', models.DateField()),
                ('indian', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.indian')),
            ],
        ),
    ]
