# Generated by Django 3.2 on 2024-06-23 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aadhardetail',
            name='indian',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='myapp.indian'),
        ),
    ]
