# Generated by Django 3.2 on 2024-06-23 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_aadhardetail_indian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aadhardetail',
            name='indian',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.indian'),
        ),
    ]
